apiVersion: v1
kind: ReplicaSet
metadata:
  name: kubia-rs
  labels:
    app: kubia
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: luksa/kubia
        ports:
        - containerPort: 80
          protocol: TCP